openapi: 3.2.0
info:
    title: User Service
    description: Service for handling user-related operations
    version: 0.0.1
servers:
    - url: http://localhost:8080
      name: user-service
paths:
    /health:
        get:
            tags:
                - health
            summary: health health
            description: Returns the health status of the service.
            operationId: health#health
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HealthResponseBody'
                            example:
                                status: ok
                "500":
                    description: 'internal_error: Fault in the service.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                            example:
                                fault: false
                                id: 123abc
                                message: parameter 'p' must be an integer
                                name: internal_error
                                temporary: false
                                timeout: false
                "503":
                    description: 'unavailable: Service unavailable.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                            example:
                                fault: false
                                id: 123abc
                                message: parameter 'p' must be an integer
                                name: unavailable
                                temporary: false
                                timeout: false
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Error response result type
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        HealthResponseBody:
            type: object
            properties:
                status:
                    type: string
                    description: Health status of the service
                    example: ok
            example:
                status: ok
            required:
                - status
tags:
    - name: health
      description: Service provides health check functionality.
